version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: bdturnos_backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    command: nodemon server

  frontend:
    build:
      context: ./frontend
    container_name: bdturnos_frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    command: npm run dev
