
services:
  backend:
    build:
      context: ./backend
    container_name: bdturnos_backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
    networks:
      - app
    command: nodemon server

  frontend:
    build:
      context: ./frontend
    container_name: bdturnos_frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    environment:
      ENV: "dev"
      API_HOST: "bdturnos_backend"
      API_PORT: "5000"
    networks:
      - app
    command: npm run dev

networks:
  app:
    driver: bridge